# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastHorseshoe <- function(Y, X, beta_hat, beta, penalize, prior_type = 1L, user_prior_function = NULL, sigma = 0.5, s2 = 4, kap2 = 16, nsamps = 10000L, burn = 1000L, skip = 10L, vglobal = 100, verb = FALSE) {
    .Call('fastHorseshoe_fastHorseshoe', PACKAGE = 'fastHorseshoe', Y, X, beta_hat, beta, penalize, prior_type, user_prior_function, sigma, s2, kap2, nsamps, burn, skip, vglobal, verb)
}

